-- Logs begin at Thu 2017-06-22 09:31:46 CST. --
Jun 22 09:49:32 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-cd2c060e-ad9f-4bb7-bfd6-619f35f80acd Date: Thu, 22 Jun 2017 01:49:32 GMT Connection: keep-alive
Jun 22 09:49:32 ubuntu nova-compute[5698]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:49:32 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:32 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-cd2c060e-ad9f-4bb7-bfd6-619f35f80acd {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:32 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}fa548fbf313af6da35cc50ad16c9bd09428f3e22" -d '{"os-detach": {"attachment_id": "54026eeb-7044-4498-8850-0ec553d5be38"}}' {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:33 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-eaa91184-466d-4e43-93c0-7d7b7e283710 Date: Thu, 22 Jun 2017 01:49:33 GMT Connection: keep-alive
Jun 22 09:49:33 ubuntu nova-compute[5698]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:49:33 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:33 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-eaa91184-466d-4e43-93c0-7d7b7e283710 {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:33 ubuntu nova-compute[5698]: DEBUG nova.notifications.objects.base [None req-5f2d892c-c4e1-4e1d-9dfb-83e36c8b830d demo demo] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object': OrphanedObjectError: Cannot call _load_projects on orphaned Flavor object {{(pid=5698) populate_schema /opt/stack/nova/nova/notifications/objects/base.py:125}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager.update_available_resource {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Auditing locally available compute resources for ubuntu (node: ubuntu) {{(pid=5698) update_available_resource /opt/stack/nova/nova/compute/resource_tracker.py:609}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.driver [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] skipping disk /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-da516c92-8307-472a-a23c-c2d89653a0bc-lun-1 (vda) as it is a volume {{(pid=5698) _get_instance_disk_info_from_config /opt/stack/nova/nova/virt/libvirt/driver.py:7125}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Hypervisor: free VCPUs: 1 {{(pid=5698) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:730}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Hypervisor/Node resource view: name=ubuntu free_ram=445MB free_disk=26GB free_vcpus=1 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "29a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_29a0", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "2981", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2981", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_01_00_0", "product_id": "4005", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1ab8", "label": "label_1ab8_4005", "address": "0000:01:00.0"}, {"dev_id": "pci_0000_00_03_0", "product_id": "4000", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1ab8", "label": "label_1ab8_4000", "address": "0000:00:03.0"}, {"dev_id": "pci_0000_00_05_0", "product_id": "1000", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1af4", "label": "label_1af4_1000", "address": "0000:00:05.0"}, {"dev_id": "pci_0000_00_0a_0", "product_id": "0022", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1011", "label": "label_1011_0022", "address": "0000:00:0a.0"}, {"dev_id": "pci_0000_00_0e_0", "product_id": "1002", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1af4", "label": "label_1af4_1002", "address": "0000:00:0e.0"}, {"dev_id": "pci_0000_00_1d_0", "product_id": "2658", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2658", "address": "0000:00:1d.0"}, {"dev_id": "pci_0000_00_1d_6", "product_id": "0194", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1033", "label": "label_1033_0194", "address": "0000:00:1d.6"}, {"dev_id": "pci_0000_00_1d_7", "product_id": "265c", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_265c", "address": "0000:00:1d.7"}, {"dev_id": "pci_0000_00_1e_0", "product_id": "244e", "dev_type": "type-PCI",
Jun 22 09:49:51 ubuntu nova-compute[5698]: "numa_node": null, "vendor_id": "8086", "label": "label_8086_244e", "address": "0000:00:1e.0"}, {"dev_id": "pci_0000_00_1f_0", "product_id": "2810", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2810", "address": "0000:00:1f.0"}, {"dev_id": "pci_0000_00_1f_1", "product_id": "244b", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_244b", "address": "0000:00:1f.1"}, {"dev_id": "pci_0000_00_1f_2", "product_id": "2821", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2821", "address": "0000:00:1f.2"}, {"dev_id": "pci_0000_00_1f_3", "product_id": "283e", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_283e", "address": "0000:00:1f.3"}, {"dev_id": "pci_0000_00_1f_4", "product_id": "2445", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2445", "address": "0000:00:1f.4"}] {{(pid=5698) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:747}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Refreshing aggregate associations for resource provider 85570fbf-8816-418b-bbba-3c11ae839dcd {{(pid=5698) _ensure_resource_provider /opt/stack/nova/nova/scheduler/client/report.py:438}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Instance cf049917-87e9-49e8-9dbd-9c1df24fe411 allocations are unchanged: MEMORY_MB=512,VCPU=1 {{(pid=5698) _allocate_for_instance /opt/stack/nova/nova/scheduler/client/report.py:836}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Total usable vcpus: 2, total allocated vcpus: 1 {{(pid=5698) _report_final_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:763}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: INFO nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Final resource view: name=ubuntu phys_ram=4927MB used_ram=1024MB phys_disk=61GB used_disk=1GB total_vcpus=2 used_vcpus=1 pci_stats=[]
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Refreshing aggregate associations for resource provider 85570fbf-8816-418b-bbba-3c11ae839dcd {{(pid=5698) _ensure_resource_provider /opt/stack/nova/nova/scheduler/client/report.py:438}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Compute_service record updated for ubuntu:ubuntu {{(pid=5698) _update_available_resource /opt/stack/nova/nova/compute/resource_tracker.py:701}}
Jun 22 09:49:51 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.399s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._heal_instance_info_cache {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Starting heal instance info cache {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5870}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Rebuilding the list of instances to heal {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5874}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Acquired semaphore "refresh_cache-cf049917-87e9-49e8-9dbd-9c1df24fe411" {{(pid=5698) lock /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:212}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG nova.network.neutronv2.api [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] _get_instance_nw_info() {{(pid=5698) _get_instance_nw_info /opt/stack/nova/nova/network/neutronv2/api.py:1284}}
Jun 22 09:49:52 ubuntu nova-compute[5698]: DEBUG nova.objects.instance [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lazy-loading 'info_cache' on Instance uuid cf049917-87e9-49e8-9dbd-9c1df24fe411 {{(pid=5698) obj_load_attr /opt/stack/nova/nova/objects/instance.py:1039}}
Jun 22 09:49:53 ubuntu nova-compute[5698]: DEBUG nova.network.base_api [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "725a32c0-27e1-46e7-83ed-49e5997d15c1", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.0.0.10"}], "version": 4, "meta": {"dhcp_server": "10.0.0.2"}, "dns": [], "routes": [], "cidr": "10.0.0.0/26", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.0.0.1"}}, {"ips": [{"meta": {}, "version": 6, "type": "fixed", "floating_ips": [], "address": "fda5:ef20:98e0:0:f816:3eff:fe4f:4c77"}], "version": 6, "meta": {"ipv6_address_mode": "slaac", "dhcp_server": "fda5:ef20:98e0:0:f816:3eff:fee5:40b4"}, "dns": [], "routes": [], "cidr": "fda5:ef20:98e0::/64", "gateway": {"meta": {}, "version": 6, "type": "gateway", "address": "fda5:ef20:98e0::1"}}], "meta": {"injected": false, "tenant_id": "6e86902b80f944a88327cb5d02f365d8", "mtu": 1450}, "id": "e45e6b65-30a8-4bbc-be21-f5a91b31d0e5", "label": "private"}, "devname": "tap725a32c0-27", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:4f:4c:77", "active": true, "type": "ovs", "id": "725a32c0-27e1-46e7-83ed-49e5997d15c1", "qbg_params": null}] {{(pid=5698) update_instance_cache_with_nw_info /opt/stack/nova/nova/network/base_api.py:43}}
Jun 22 09:49:53 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Releasing semaphore "refresh_cache-cf049917-87e9-49e8-9dbd-9c1df24fe411" {{(pid=5698) lock /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:225}}
Jun 22 09:49:53 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Updated the network info_cache for instance {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5932}}
Jun 22 09:49:53 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_unconfirmed_resizes {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:53 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._check_instance_build_time {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:54 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_rebooting_instances {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:54 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_rescued_instances {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.osapi_compute.wsgi.server [None req-4ce9abff-bdf9-4846-9059-1625b956a877 None None] (6320) accepted ('10.211.55.6', 59244) {{(pid=6320) server /usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py:883}}
Jun 22 09:49:55 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-5ae903cf-4565-41c6-a8c2-7f08d18e68ba demo demo] 10.211.55.6 "GET /v2.1 HTTP/1.1" status: 302 len: 313 time: 0.0271320
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-9b7984a5-0507-44b2-bf26-e699cde7d6ae demo demo] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7efc146c1750>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:49:55 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-9b7984a5-0507-44b2-bf26-e699cde7d6ae demo demo] 10.211.55.6 "GET /v2.1/ HTTP/1.1" status: 200 len: 784 time: 0.0269070
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7efc1412a990>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Fetching instance by UUID {{(pid=6320) get /opt/stack/nova/nova/compute/api.py:2453}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.policy [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] Policy check for os_compute_api:os-extended-server-attributes failed with credentials {'service_roles': [], 'user_id': u'7a282530f0c74dbfb711eba70ebf3ea4', 'roles': [u'anotherrole', u'Member'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': False, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:os-extended-server-attributes to be performed. {{(pid=6320) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.policy [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] Policy check for os_compute_api:servers:show:host_status failed with credentials {'service_roles': [], 'user_id': u'7a282530f0c74dbfb711eba70ebf3ea4', 'roles': [u'anotherrole', u'Member'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': False, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:servers:show:host_status to be performed. {{(pid=6320) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:49:55 ubuntu nova-scheduler[5687]: DEBUG oslo_service.periodic_task [None req-b0b9dd1d-827b-4339-af55-e82847c70790 None None] Running periodic task SchedulerManager._expire_reservations {{(pid=5687) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:55 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-bc181f27-0a04-400e-80ed-729a862be32c demo demo] 10.211.55.6 "GET /v2.1/servers/cf049917-87e9-49e8-9dbd-9c1df24fe411 HTTP/1.1" status: 200 len: 1916 time: 0.3120990
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Action: 'create', calling method: <bound method VolumeAttachmentController.create of <nova.api.openstack.compute.volumes.VolumeAttachmentController object at 0x7efc14649210>>, body: {"volumeAttachment": {"volumeId": "157e27cd-2edf-4ef0-accc-9b023620f26f"}} {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:621}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Fetching instance by UUID {{(pid=6320) get /opt/stack/nova/nova/compute/api.py:2453}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:55 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "cf049917-87e9-49e8-9dbd-9c1df24fe411" acquired by "nova.compute.manager.do_reserve" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:55 ubuntu nova-compute[5698]: DEBUG nova.objects.instance [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lazy-loading 'flavor' on Instance uuid cf049917-87e9-49e8-9dbd-9c1df24fe411 {{(pid=5698) obj_load_attr /opt/stack/nova/nova/objects/instance.py:1039}}
Jun 22 09:49:55 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "cf049917-87e9-49e8-9dbd-9c1df24fe411" released by "nova.compute.manager.do_reserve" :: held 0.075s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:55 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] REQ: curl -g -i -X GET http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f -H "X-Service-Token: {SHA1}6349ac7419ee673e10b7cd665fb673dfb272ad86" -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}2cb1f1999845d124eead312a5f23ec571b0ff709" {{(pid=6320) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:56 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] RESP: [200] X-Compute-Request-Id: req-82ba0c10-6c06-48dd-a488-5adc5e7eafd3 Content-Type: application/json Content-Length: 887 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-82ba0c10-6c06-48dd-a488-5adc5e7eafd3 Date: Thu, 22 Jun 2017 01:49:56 GMT Connection: keep-alive
Jun 22 09:49:56 ubuntu nova-api[5615]: RESP BODY: {"volume": {"status": "available", "user_id": "7a282530f0c74dbfb711eba70ebf3ea4", "attachments": [], "links": [{"href": "http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "self"}, {"href": "http://10.211.55.6:8776/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2017-06-20T06:48:14.000000", "description": null, "os-vol-tenant-attr:tenant_id": "6e86902b80f944a88327cb5d02f365d8", "updated_at": "2017-06-22T01:49:32.000000", "volume_type": "lvmdriver-1", "name": "cin04", "replication_status": null, "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {"readonly": "False"}, "id": "157e27cd-2edf-4ef0-accc-9b023620f26f", "size": 1}}
Jun 22 09:49:56 ubuntu nova-api[5615]:  {{(pid=6320) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:56 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] GET call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f used request id req-82ba0c10-6c06-48dd-a488-5adc5e7eafd3 {{(pid=6320) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:56 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "X-Service-Token: {SHA1}6349ac7419ee673e10b7cd665fb673dfb272ad86" -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}2cb1f1999845d124eead312a5f23ec571b0ff709" -d '{"os-reserve": null}' {{(pid=6320) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_volume_usage {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:56 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-2f80f1eb-3d97-461e-84b1-b030adb8d403 Date: Thu, 22 Jun 2017 01:49:56 GMT Connection: keep-alive
Jun 22 09:49:56 ubuntu nova-api[5615]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:49:56 ubuntu nova-api[5615]:  {{(pid=6320) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:56 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-2f80f1eb-3d97-461e-84b1-b030adb8d403 {{(pid=6320) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:56 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] 10.211.55.6 "POST /v2.1/servers/cf049917-87e9-49e8-9dbd-9c1df24fe411/os-volume_attachments HTTP/1.1" status: 200 len: 595 time: 0.3719749
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "cf049917-87e9-49e8-9dbd-9c1df24fe411" acquired by "nova.compute.manager.do_attach_volume" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: INFO nova.compute.manager [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Attaching volume 157e27cd-2edf-4ef0-accc-9b023620f26f to /dev/vdb
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG nova.objects.instance [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lazy-loading 'flavor' on Instance uuid cf049917-87e9-49e8-9dbd-9c1df24fe411 {{(pid=5698) obj_load_attr /opt/stack/nova/nova/objects/instance.py:1039}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG nova.notifications.objects.base [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object': OrphanedObjectError: Cannot call _load_projects on orphaned Flavor object {{(pid=5698) populate_schema /opt/stack/nova/nova/notifications/objects/base.py:125}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] REQ: curl -g -i -X GET http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}2cb1f1999845d124eead312a5f23ec571b0ff709" {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] RESP: [200] X-Compute-Request-Id: req-603308ab-5a47-48af-b4b6-3ed23dde97f8 Content-Type: application/json Content-Length: 887 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-603308ab-5a47-48af-b4b6-3ed23dde97f8 Date: Thu, 22 Jun 2017 01:49:56 GMT Connection: keep-alive
Jun 22 09:49:56 ubuntu nova-compute[5698]: RESP BODY: {"volume": {"status": "attaching", "user_id": "7a282530f0c74dbfb711eba70ebf3ea4", "attachments": [], "links": [{"href": "http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "self"}, {"href": "http://10.211.55.6:8776/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2017-06-20T06:48:14.000000", "description": null, "os-vol-tenant-attr:tenant_id": "6e86902b80f944a88327cb5d02f365d8", "updated_at": "2017-06-22T01:49:56.000000", "volume_type": "lvmdriver-1", "name": "cin04", "replication_status": null, "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {"readonly": "False"}, "id": "157e27cd-2edf-4ef0-accc-9b023620f26f", "size": 1}}
Jun 22 09:49:56 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] GET call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f used request id req-603308ab-5a47-48af-b4b6-3ed23dde97f8 {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG os_brick.utils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '10.211.55.6', 'enforce_multipath': True, 'host': 'ubuntu', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:146}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.003s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('## DO NOT EDIT OR REMOVE THIS FILE!\n## If you remove this file, the iSCSI daemon will not start.\n## If you change the InitiatorName, existing access control lists\n## may reject this initiator.  The InitiatorName must be unique\n## for each iSCSI initiator.  Do NOT duplicate iSCSI InitiatorNames.\nInitiatorName=iqn.1993-08.org.debian:01:e46cdd201069\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxfc [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] No Fibre Channel support detected on system. {{(pid=5698) get_fc_hbas /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxfc.py:89}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxfc [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] No Fibre Channel support detected on system. {{(pid=5698) get_fc_hbas /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxfc.py:89}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG os_brick.utils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] <== get_connector_properties: return (6ms) {'initiator': u'iqn.1993-08.org.debian:01:e46cdd201069', 'ip': u'10.211.55.6', 'platform': u'x86_64', 'host': u'ubuntu', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:170}}
Jun 22 09:49:56 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}2cb1f1999845d124eead312a5f23ec571b0ff709" -d '{"os-initialize_connection": {"connector": {"platform": "x86_64", "host": "ubuntu", "do_local_attach": false, "ip": "10.211.55.6", "os_type": "linux2", "multipath": false, "initiator": "iqn.1993-08.org.debian:01:e46cdd201069"}}}' {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] RESP: [200] X-Compute-Request-Id: req-d6d91782-7de1-4b11-b1cb-db95756e6ec6 Content-Type: application/json Content-Length: 445 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-d6d91782-7de1-4b11-b1cb-db95756e6ec6 Date: Thu, 22 Jun 2017 01:49:57 GMT Connection: keep-alive
Jun 22 09:49:57 ubuntu nova-compute[5698]: RESP BODY: {"connection_info": {"driver_volume_type": "iscsi", "data": {"auth_password": "5P6QLBpXJB9z9eTL", "target_discovered": false, "encrypted": false, "qos_specs": null, "target_iqn": "iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f", "target_portal": "10.211.55.6:3260", "volume_id": "157e27cd-2edf-4ef0-accc-9b023620f26f", "target_lun": 1, "access_mode": "rw", "auth_username": "o7mWUDheAUxfFJJJVB3g", "auth_method": "CHAP"}}}
Jun 22 09:49:57 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-d6d91782-7de1-4b11-b1cb-db95756e6ec6 {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.volume.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Calling os-brick to attach iSCSI Volume {{(pid=5698) connect_volume /opt/stack/nova/nova/virt/libvirt/volume/iscsi.py:63}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] ==> connect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x7fba61c7de90>, {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', u'target_portal': u'10.211.55.6:3260', u'volume_id': u'157e27cd-2edf-4ef0-accc-9b023620f26f', u'target_lun': 1, u'auth_password': u'***', u'auth_username': u'o7mWUDheAUxfFJJJVB3g', u'auth_method': u'CHAP'}), 'kwargs': {}}" {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:146}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.connect_volume" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: INFO os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Multipath discovery for iSCSI not enabled.
Jun 22 09:49:57 ubuntu nova-compute[5698]: INFO os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Trying to connect to iSCSI portal 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260" returned: 21 in 0.004s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260' failed. Not Retrying. {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:433}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: Exception during request[140438185893072]: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:449}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: Traceback (most recent call last):
Jun 22 09:49:57 ubuntu nova-compute[5698]:   File "/usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py", line 445, in loop
Jun 22 09:49:57 ubuntu nova-compute[5698]:     reply = self._process_cmd(*msg)
Jun 22 09:49:57 ubuntu nova-compute[5698]:   File "/usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py", line 428, in _process_cmd
Jun 22 09:49:57 ubuntu nova-compute[5698]:     ret = func(*f_args, **f_kwargs)
Jun 22 09:49:57 ubuntu nova-compute[5698]:   File "/usr/local/lib/python2.7/dist-packages/oslo_privsep/priv_context.py", line 207, in _wrap
Jun 22 09:49:57 ubuntu nova-compute[5698]:     return func(*args, **kwargs)
Jun 22 09:49:57 ubuntu nova-compute[5698]:   File "/usr/local/lib/python2.7/dist-packages/os_brick/privileged/rootwrap.py", line 82, in execute_root
Jun 22 09:49:57 ubuntu nova-compute[5698]:     return putils.execute(*cmd, shell=False, run_as_root=False, **kwargs)
Jun 22 09:49:57 ubuntu nova-compute[5698]:   File "/usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py", line 400, in execute
Jun 22 09:49:57 ubuntu nova-compute[5698]:     cmd=sanitized_cmd)
Jun 22 09:49:57 ubuntu nova-compute[5698]: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n'
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (5, 'oslo_concurrency.processutils.ProcessExecutionError', (u'', u'iscsiadm: No records found\n', 21, u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260', None)) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--interface', 'default', '--op', 'new'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --interface default --op new {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --interface default --op new" returned: 0 in 0.005s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 10.211.55.6,3260,-1 iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f] added\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--interface', 'default', '--op', 'new'): stdout=New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 10.211.55.6,3260,-1 iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f] added
Jun 22 09:49:57 ubuntu nova-compute[5698]:  stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.authmethod -v CHAP {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.authmethod -v CHAP" returned: 0 in 0.004s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'): stdout= stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'update', '-n', 'node.session.auth.username', '-v', u'o7mWUDheAUxfFJJJVB3g'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.username -v o7mWUDheAUxfFJJJVB3g {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.username -v o7mWUDheAUxfFJJJVB3g" returned: 0 in 0.004s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--op', 'update', '-n', 'node.session.auth.username', '-v', u'o7mWUDheAUxfFJJJVB3g'): stdout= stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'update', '-n', 'node.session.auth.password', '-v', u'5P6QLBpXJB9z9eTL'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.password -v *** {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.session.auth.password -v ***" returned: 0 in 0.006s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--op', 'update', '-n', 'node.session.auth.password', '-v', u'***'): stdout= stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'session'), {'check_exit_code': (0, 1, 21)}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m session {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m session" returned: 0 in 0.004s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('tcp: [1] 10.211.55.6:3260,1 iqn.2010-10.org.openstack:volume-da516c92-8307-472a-a23c-c2d89653a0bc (non-flash)\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ['-m', 'session']: stdout=tcp: [1] 10.211.55.6:3260,1 iqn.2010-10.org.openstack:volume-da516c92-8307-472a-a23c-c2d89653a0bc (non-flash)
Jun 22 09:49:57 ubuntu nova-compute[5698]:  stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:57 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:57 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:57 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm_bare /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:841}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--login'), {'attempts': 1, 'check_exit_code': (0, 255), 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --login {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._instance_usage_audit {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._reclaim_queued_deletes {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] CONF.reclaim_instance_interval <= 0, skipping... {{(pid=5698) _reclaim_queued_deletes /opt/stack/nova/nova/compute/manager.py:6535}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --login" returned: 0 in 1.364s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] (multiple)\nLogin to [iface: default, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] successful.\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--login',): stdout=Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] (multiple)
Jun 22 09:49:58 ubuntu nova-compute[5698]: Login to [iface: default, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] successful.
Jun 22 09:49:58 ubuntu nova-compute[5698]:  stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:58 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:58 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:58 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:58 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'update', '-n', 'node.startup', '-v', 'automatic'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.startup -v automatic {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.startup -v automatic" returned: 0 in 0.012s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'automatic'): stdout= stderr=: ProcessExecutionError: Unexpected error while running command.
Jun 22 09:49:58 ubuntu nova-compute[5698]: Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260
Jun 22 09:49:58 ubuntu nova-compute[5698]: Exit code: 21
Jun 22 09:49:58 ubuntu nova-compute[5698]: Stdout: u''
Jun 22 09:49:58 ubuntu nova-compute[5698]: Stderr: u'iscsiadm: No records found\n' {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: INFO os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] ISCSI volume not yet found at: [u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1']. Will rescan & retry.  Try number: 0.
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--rescan'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --rescan {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --rescan" returned: 0 in 0.068s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('Rescanning session [sid: 4, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260]\n', 'iscsiadm: invalid error code 65280\niscsiadm: Could not execute operation on all sessions: (null)\n')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] iscsiadm ('--rescan',): stdout=Rescanning session [sid: 4, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260]
Jun 22 09:49:58 ubuntu nova-compute[5698]:  stderr=iscsiadm: invalid error code 65280
Jun 22 09:49:58 ubuntu nova-compute[5698]: iscsiadm: Could not execute operation on all sessions: (null)
Jun 22 09:49:58 ubuntu nova-compute[5698]:  {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Found iSCSI node [u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1'] (after 1 rescans) {{(pid=5698) connect_volume /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:452}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438185893072]: (3, 'os_brick.privileged.rootwrap.execute_root', ('/lib/udev/scsi_id', '--page', '0x83', '--whitelisted', u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1'), {}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): /lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1 {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "/lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1" returned: 0 in 0.005s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438185893072]: (4, ('360000000000000000e00000000060001\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Device WWN = '360000000000000000e00000000060001' {{(pid=5698) connect_volume /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:459}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] connect_volume returning {'path': u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1', 'scsi_wwn': u'360000000000000000e00000000060001', 'type': 'block'} {{(pid=5698) connect_volume /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:471}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.connect_volume" :: held 1.516s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] <== connect_volume: return (1516ms) {'path': u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1', 'scsi_wwn': u'360000000000000000e00000000060001', 'type': u'block'} {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:170}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.volume.iscsi [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Attached iSCSI volume {'path': u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1', 'scsi_wwn': u'360000000000000000e00000000060001', 'type': 'block'} {{(pid=5698) connect_volume /opt/stack/nova/nova/virt/libvirt/volume/iscsi.py:65}}
Jun 22 09:49:58 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.guest [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] attach device xml: <disk type="block" device="disk">
Jun 22 09:49:58 ubuntu nova-compute[5698]:   <driver name="qemu" type="raw" cache="none" io="native"/>
Jun 22 09:49:58 ubuntu nova-compute[5698]:   <source dev="/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1"/>
Jun 22 09:49:58 ubuntu nova-compute[5698]:   <target bus="virtio" dev="vdb"/>
Jun 22 09:49:58 ubuntu nova-compute[5698]:   <serial>157e27cd-2edf-4ef0-accc-9b023620f26f</serial>
Jun 22 09:49:58 ubuntu nova-compute[5698]: </disk>
Jun 22 09:49:58 ubuntu nova-compute[5698]:  {{(pid=5698) attach_device /opt/stack/nova/nova/virt/libvirt/guest.py:309}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._sync_scheduler_instance_info {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:49:59 ubuntu nova-scheduler[5687]: DEBUG oslo_concurrency.lockutils [None req-f4e268e5-7dbb-4cfa-aaee-f28d7cdde6cb None None] Lock "host_instance" acquired by "nova.scheduler.host_manager.sync_instance_info" :: waited 0.000s {{(pid=5687) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:49:59 ubuntu nova-scheduler[5687]: INFO nova.scheduler.host_manager [None req-f4e268e5-7dbb-4cfa-aaee-f28d7cdde6cb None None] Successfully synced instances from host 'ubuntu'.
Jun 22 09:49:59 ubuntu nova-scheduler[5687]: DEBUG oslo_concurrency.lockutils [None req-f4e268e5-7dbb-4cfa-aaee-f28d7cdde6cb None None] Lock "host_instance" released by "nova.scheduler.host_manager.sync_instance_info" :: held 0.001s {{(pid=5687) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}2cb1f1999845d124eead312a5f23ec571b0ff709" -d '{"os-attach": {"instance_uuid": "cf049917-87e9-49e8-9dbd-9c1df24fe411", "mountpoint": "/dev/vdb", "mode": "rw"}}' {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-60987573-9278-4609-8625-b412ce200dc7 Date: Thu, 22 Jun 2017 01:49:59 GMT Connection: keep-alive
Jun 22 09:49:59 ubuntu nova-compute[5698]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:49:59 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-60987573-9278-4609-8625-b412ce200dc7 {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG nova.notifications.objects.base [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object': OrphanedObjectError: Cannot call _load_projects on orphaned Flavor object {{(pid=5698) populate_schema /opt/stack/nova/nova/notifications/objects/base.py:125}}
Jun 22 09:49:59 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-d2346cca-2b88-4e79-b9bc-d840bff5db10 demo demo] Lock "cf049917-87e9-49e8-9dbd-9c1df24fe411" released by "nova.compute.manager.do_attach_volume" :: held 3.399s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
